#!/bin/bash
#
## Reload and restart Plex
echo "Reloading daemons."
sudo systemctl daemon-reload && echo "Done."
echo "Stopping Plex Service"
sudo systemctl stop plexmediaserver.service && echo "Done."
echo "Starting Plex Service"
sudo systemctl start plexmediaserver.service && echo "Done."
