#!/bin/bash

sonarrDir="/var/lib/sonarr"
srcSrv="/home/brian/doc/src/bash-misc/sonarr.service"
sonarrSrv="/usr/lib/systemd/system/sonarr.service"
#
## Fix permissions on SabNZBd+ directory
echo "Fixing ownership." ; sudo chown -R brian "$sonarrDir" && echo "Done."
echo "Fixing group." ; sudo chgrp -R users "$sonarrDir" && echo "Done."
#
# Restore service file
echo "Copy file."
sudo cp "$srcSrv" "$sonarrSrv" && echo "Done."
echo "Restore ownership."
sudo chown root "$sonarrSrv" && echo "Done."
echo "Restore group."
sudo chgrp root "$sonarrSrv" && echo "Done."
echo "Restore permissions."
sudo chmod 644 "$sonarrSrv" && echo "Done."

echo "Reloading daemons."
sudo systemctl daemon-reload && echo "Done."
echo "Stopping Sonarr Service"
sudo systemctl stop sonarr.service && echo "Done."
echo "Starting Sonarr Service"
sudo systemctl start sonarr.service && echo "Done."
